extends RefCounted
class_name BattleTuning

const HUD_SECTION_TITLE_SIZE := 28
const HUD_STAT_FONT_SIZE := 22
const HUD_STATUS_FONT_SIZE := 18
const HUD_BUTTON_FONT_SIZE := 22
const HUD_ANCHOR_FONT_SIZE := 24
const DEBUG_TITLE_FONT_SIZE := 14
const DEBUG_FONT_SIZE := 11
const DEBUG_PANEL_MODULATE := Color(0.78, 0.8, 0.88, 0.82)
const HUD_BAR_HEIGHT := 26.0
const HUD_END_TURN_BUTTON_SIZE := Vector2(240.0, 58.0)
const BOARD_PANEL_MIN_HEIGHT := 500.0
const DEBUG_PANEL_WIDTH := 320.0

const HAND_CARD_WIDTH := 224.0
const HAND_CARD_HEIGHT := 188.0
const HAND_CARD_SPACING := 242.0
const HAND_HORIZONTAL_PADDING := 32.0
const HAND_START_Y := 26.0
const HAND_PANEL_HEIGHT := 320.0
const HAND_AREA_HEIGHT := 250.0
const HAND_EMPTY_LABEL_POSITION := Vector2(24.0, 56.0)
const HAND_HEADER_FONT_SIZE := 22
const HAND_CARD_TITLE_SIZE := 20
const HAND_CARD_BODY_SIZE := 15
const HAND_CARD_COST_SIZE := 24
const HAND_CARD_ROW_LABEL_SIZE := 13
const HAND_CARD_ROW_VALUE_SIZE := 16
const HAND_CARD_ROW_KEY_WIDTH := 62.0
const HAND_CARD_ROW_MIN_HEIGHT := 24.0
const HAND_CARD_ROW_SEPARATION := 6
const HAND_HOVER_LIFT := 26.0
const HAND_HOVER_SCALE := 1.06
const HAND_UNFOCUSED_SCALE := 0.97
const HAND_UNFOCUSED_MODULATE := Color(0.84, 0.84, 0.88, 1.0)
const HAND_HOVER_Z_INDEX := 10

const CARD_DETAIL_TITLE_SIZE := 14
const CARD_DETAIL_NAME_SIZE := 18
const CARD_DETAIL_BODY_SIZE := 14

const ENERGY_SHAKE_LEFT_DISTANCE := -12.0
const ENERGY_SHAKE_RIGHT_DISTANCE := 10.0
const ENERGY_SHAKE_RETURN_DISTANCE := -6.0
const ENERGY_SHAKE_STEP_ONE := 0.03
const ENERGY_SHAKE_STEP_TWO := 0.04
const ENERGY_SHAKE_STEP_THREE := 0.04
const ENERGY_SHAKE_STEP_FOUR := 0.05
const PULSE_FADE_TIME := 0.22

const ATTACK_FLIGHT_TIME := 0.14
const IMPACT_PUSH_DISTANCE := 18.0
const IMPACT_HIT_STOP_TIME := 0.04
const IMPACT_RETURN_TIME := 0.08
const IMPACT_BLOCK_REVERSE_SCALE := -0.6
const HP_TRACK_TWEEN_TIME := 0.09

const CHAIN_INTERVAL := 0.08
const CHAIN_COMPRESSED_INTERVAL := 0.04
const CHAIN_COMPRESS_HIT_THRESHOLD := 4
const BLOCK_TO_HP_GAP := 0.03

const FLOAT_TEXT_RISE_DISTANCE := 24.0
const FLOAT_TEXT_MOVE_TIME := 0.28
const FLOAT_TEXT_FADE_TIME := 0.22

const TOTAL_RISE_DISTANCE := 18.0
const TOTAL_POPUP_LIFETIME := 0.28
const TOTAL_INTERRUPT_TIME := 0.06

const FX_LAYER_Z_ATTACK := 10
const FX_LAYER_Z_TOTAL := 20
const FX_LAYER_Z_DAMAGE := 30